server:
  port: 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: tfprojarq
          uri: lb://tfprojarq
          predicates:
            - Path=/tfprojarq/**
          filters:
            - RewritePath=/tfprojarq/(?<resto>.*), /servcad/${resto}
        - id: Asscache
          uri: lb://Asscache
          predicates:
            - Path=/Asscache/**
          filters:
            - RewritePath=/Asscache/(?<resto>.*), /validate/${resto}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

